/**
 * Apps Script Web App — the single entry point between the practice web app
 * and Google Sheets / Google Drive.
 *
 * DEPLOYMENT — READ BEFORE PASTING:
 *   This file alone is NOT enough. `Contract` (js/contract.js) and
 *   `parseLessonRow` (js/lesson.js, task T2) must ALSO be pasted into this
 *   same Apps Script project as a file named `Shared.gs` (per the project's
 *   deploy convention — see docs). This file calls `Contract.*` and
 *   `parseLessonRow(row)` as plain globals; it does not (and, in the Apps
 *   Script V8 runtime, cannot) `require`/`import` them.
 *
 *   One-time setup, in order:
 *     1. Create/open the "English Learning" Google Sheet.
 *     2. Extensions > Apps Script. This creates a script bound to that sheet.
 *     3. Paste js/contract.js + js/lesson.js content into a file `Shared.gs`.
 *     4. Paste this file's content into `Code.gs`.
 *     5. Run `setupSheets` once (Apps Script editor > select function > Run).
 *     6. Run `generateToken` once and copy the printed token into the app's
 *        local config on every device that will sync (see js/config.local.js,
 *        not checked into version control).
 *     7. Deploy > New deployment > Web app > Execute as: Me,
 *        Who has access: Anyone. Copy the deployment URL into the app config.
 *
 * SCRIPT PROPERTIES (Project Settings > Script Properties):
 *   SYNC_TOKEN      required. Long random string. Generated by generateToken().
 *   SPREADSHEET_ID  optional. Only needed if this script is NOT bound to the
 *                   "English Learning" sheet (i.e. running as a standalone
 *                   script). When absent, SpreadsheetApp.getActiveSpreadsheet()
 *                   is used, which only works for a container-bound script.
 *
 * SOURCE OF TRUTH:
 *   docs/specs/2026-09-02-practice-web-app.md  (API contract table, access
 *     control decision, Sheets schema)
 *   docs/specs/2026-09-02-content-pipeline.md  (lessons sheet schema)
 *   js/contract.js                             (shared constants)
 *
 * IMPORTANT LIMITATION — no real HTTP status codes:
 *   Apps Script web apps always respond with HTTP 200; there is no API to
 *   set a different status code (e.g. 403 Forbidden) on the response. Every
 *   failure — including a bad auth token — is therefore signalled through
 *   the JSON body's `ok`/`error` fields instead. Callers must check `ok`,
 *   never the HTTP status.
 */

// ---------------------------------------------------------------------------
// Entry points
// ---------------------------------------------------------------------------

function doGet(e) {
  return route(e);
}

function doPost(e) {
  return route(e);
}

/**
 * Shared router for both GET and POST. `token` and `action` always arrive as
 * URL query parameters (e.parameter) even on POST requests; the POST body
 * (e.postData.contents) carries only the action-specific JSON payload.
 */
function route(e) {
  try {
    var params = (e && e.parameter) || {};

    if (!isValidToken(params.token)) {
      return jsonOutput({ ok: false, error: 'forbidden' });
    }

    switch (params.action) {
      case Contract.ACTIONS.LESSONS:
        return actionLessons(params);
      case Contract.ACTIONS.AUDIO:
        return actionAudio(params);
      case Contract.ACTIONS.PROGRESS:
        return actionProgress(params);
      case Contract.ACTIONS.APPEND:
        return actionAppend(e);
      case Contract.ACTIONS.SET_LEVEL:
        return actionSetLevel(e);
      // Matched against the literal, not only Contract.ACTIONS.ADD_MATERIALS.
      // Shared.gs is pasted in by hand and can lag behind this file; when it
      // does, that constant is undefined, no switch case ever matches it, and
      // the request falls through to unknown_action with nothing pointing at
      // the real cause (a stale paste). Accepting the literal keeps this
      // action working across that gap.
      case 'add_materials':
        return actionAddMaterials(e);
      default:
        return jsonOutput({ ok: false, error: 'unknown_action' });
    }
  } catch (err) {
    // Last-resort catch-all so a bug in one action never surfaces as a raw
    // Apps Script HTML error page — the client always gets JSON back.
    //
    // The full error (which can contain spreadsheet ids, sheet names, or
    // internal function names) is logged server-side only, via
    // console.error — never in the response body.
    console.error('[route] unhandled error: ' + ((err && err.stack) || (err && err.message) || err));
    return jsonOutput({
      ok: false,
      error: 'internal_error'
    });
  }
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

/**
 * action=lessons — read the `lessons` sheet, optionally filtered to rows
 * after `since` (a lesson_id / YYYY-MM-DD date, compared lexicographically).
 *
 * Broken rows are NEVER dropped silently: every row that parseLessonRow()
 * flags is reported in `errors`, tagged with its sheet row number and raw
 * lesson_id (if readable), so the web app can tell the user which day's
 * content is broken instead of just seeing it vanish.
 */
function actionLessons(params) {
  var sheet = getSheetByName(Contract.SHEETS.LESSONS);
  if (!sheet) {
    return jsonOutput({ ok: false, error: 'sheet_not_found', sheet: Contract.SHEETS.LESSONS });
  }

  var lastRow = sheet.getLastRow();
  if (lastRow < 2) {
    return jsonOutput({ ok: true, lessons: [], errors: [] });
  }

  var values = sheet.getRange(2, 1, lastRow - 1, Contract.LESSON_COLUMNS.length).getValues();
  var since = params.since || null;

  var lessons = [];
  var errors = [];
  var materials = [];

  // The web app never wants material rows; the daily health check does, both
  // to report how many days of lessons are left and to include their
  // source_urls in the duplicate check. Off by default so the app's payload
  // stays small -- one flag rather than a second endpoint, because the two
  // callers want the same rows read the same way.
  var includeMaterials = params.include_materials === '1' ||
    params.include_materials === 'true';

  values.forEach(function (row, idx) {
    var rawLessonId = row[0] ? String(row[0]) : '';

    // An empty lesson_id marks a "material row" (source text + audio ready,
    // no questions yet — written by action=add_materials, filled in later
    // by Spark; see docs/specs/2026-09-02-content-pipeline.md). That is a
    // normal inventory state, not a broken row: never returned in `lessons`
    // (nothing to render without questions) and never in `errors`
    // (parseLessonRow would flag MISSING_FIELD, which would be misleading).
    if (!rawLessonId) {
      if (includeMaterials) {
        materials.push(rowToObject(row, idx + 2));
      }
      return;
    }

    // `since` is exclusive: only rows strictly after it are returned. Rows
    // with an unreadable lesson_id are kept (not skipped) so a broken recent
    // row still surfaces in `errors` instead of disappearing.
    if (since && rawLessonId && rawLessonId <= since) {
      return;
    }

    var result = parseLessonRow(row);
    if (result.lesson) {
      lessons.push(result.lesson);
    }
    if (result.errors && result.errors.length > 0) {
      errors.push({
        row: idx + 2, // 1-based sheet row, +1 for header
        lesson_id: rawLessonId || null,
        errors: result.errors
      });
    }
  });

  var payload = { ok: true, lessons: lessons, errors: errors };
  if (includeMaterials) {
    payload.materials = materials;
    payload.material_count = materials.length;
  }
  return jsonOutput(payload);
}

/** Maps a raw sheet row onto its column names, for callers that want it whole. */
function rowToObject(row, sheetRow) {
  var obj = { _row: sheetRow };
  Contract.LESSON_COLUMNS.forEach(function (name, i) {
    obj[name] = row[i];
  });
  return obj;
}

/**
 * action=audio — proxy a Drive-hosted MP3 through the Web App.
 *
 * CHOSEN APPROACH: base64-encode the file bytes and return them inside the
 * same JSON envelope as every other action ({ok, base64, mime_type, ...}).
 *
 * Why: Apps Script's ContentService can only emit text-based MIME types
 * (JSON/TEXT/XML/...); there is no `createBinaryOutput` for web apps, so a
 * raw audio/mpeg response is not an option. The alternative — making the
 * Drive file link-public and letting the browser fetch it directly — is
 * exactly what the practice-web-app spec rules out (CORS + quota, and it
 * would require changing Drive file sharing away from private).
 *
 * Cost: base64 inflates payload size by ~33%, and the whole file is loaded
 * into Apps Script's memory and JSON-serialized in one shot (no streaming).
 * For the lesson-length clips this pipeline produces (single MP3s, not
 * pre-trimmed per spec) this is acceptable but not free — expect this call
 * to be the slowest one in the API, and the client should cache the decoded
 * result (e.g. as a Blob) rather than re-fetching per playback.
 */
function actionAudio(params) {
  var fileId = params.file_id;
  if (!fileId) {
    return jsonOutput({ ok: false, error: 'missing_file_id' });
  }

  // Only file ids that actually appear in the lessons sheet's audio_file_id
  // column may be read — otherwise anyone holding the sync token could pass
  // an arbitrary Drive file id and read back any file the deploying account
  // can access. See buildAudioFileIdAllowlist_/isAllowedAudioFileId_ below.
  if (!isAllowedAudioFileId_(fileId)) {
    return jsonOutput({ ok: false, error: 'forbidden' });
  }

  try {
    var file = DriveApp.getFileById(fileId);
    var blob = file.getBlob();
    var base64 = Utilities.base64Encode(blob.getBytes());
    return jsonOutput({
      ok: true,
      file_id: fileId,
      mime_type: blob.getContentType(),
      filename: file.getName(),
      base64: base64
    });
  } catch (err) {
    return jsonOutput({ ok: false, error: 'not_found', file_id: fileId });
  }
}

/**
 * Cache key/TTL for the audio_file_id allowlist used by actionAudio. Kept
 * short (5 minutes) so a file_id added by AudioFetcher.gs today becomes
 * playable the same day without a manual step — worst case, a freshly
 * fetched lesson's audio is briefly rejected until the cache naturally
 * expires (or immediately, whenever the cache had already expired/missed).
 */
var AUDIO_ALLOWLIST_CACHE_KEY = 'audio_file_id_allowlist';
var AUDIO_ALLOWLIST_CACHE_TTL_SEC = 300;

/**
 * True only if `fileId` is one of the values actually present in the
 * lessons sheet's audio_file_id column (column O). This is what stops
 * action=audio from being an arbitrary-Drive-file read primitive (see
 * actionAudio's comment).
 */
function isAllowedAudioFileId_(fileId) {
  var cache = CacheService.getScriptCache();
  var cached = cache.get(AUDIO_ALLOWLIST_CACHE_KEY);
  var allowlist;
  if (cached) {
    allowlist = JSON.parse(cached);
  } else {
    allowlist = buildAudioFileIdAllowlist_();
    try {
      cache.put(AUDIO_ALLOWLIST_CACHE_KEY, JSON.stringify(allowlist), AUDIO_ALLOWLIST_CACHE_TTL_SEC);
    } catch (e) {
      // CacheService caps a single value at 100KB. If the allowlist ever
      // grows past that, just skip caching this round — every request
      // rebuilds it from the sheet, which is correct, just not free.
    }
  }
  return allowlist.indexOf(String(fileId)) !== -1;
}

/** Reads the full audio_file_id column and returns the non-empty values. */
function buildAudioFileIdAllowlist_() {
  var sheet = getSheetByName(Contract.SHEETS.LESSONS);
  if (!sheet) return [];

  var lastRow = sheet.getLastRow();
  if (lastRow < 2) return [];

  var idxAudioFileId = Contract.LESSON_COLUMNS.indexOf('audio_file_id');
  var values = sheet.getRange(2, idxAudioFileId + 1, lastRow - 1, 1).getValues();

  var ids = [];
  values.forEach(function (row) {
    if (row[0]) ids.push(String(row[0]));
  });
  return ids;
}

/**
 * action=progress — all answer records after `since` (ISO8601 UTC, exclusive).
 */
function actionProgress(params) {
  var sheet = getSheetByName(Contract.SHEETS.PROGRESS);
  if (!sheet) {
    return jsonOutput({ ok: false, error: 'sheet_not_found', sheet: Contract.SHEETS.PROGRESS });
  }

  var lastRow = sheet.getLastRow();
  if (lastRow < 2) {
    return jsonOutput({ ok: true, records: [] });
  }

  var since = params.since || null;
  var answeredAtIndex = Contract.PROGRESS_COLUMNS.indexOf('answered_at');
  var values = sheet.getRange(2, 1, lastRow - 1, Contract.PROGRESS_COLUMNS.length).getValues();

  var records = values
    .filter(function (row) {
      if (!since) return true;
      var answeredAt = row[answeredAtIndex];
      return !!answeredAt && String(answeredAt) > since;
    })
    .map(rowToProgressRecord);

  return jsonOutput({ ok: true, records: records });
}

/**
 * action=append (POST) — append new answer records, deduped by record_id.
 *
 * Concurrency: phone and desktop can both come back online and upload their
 * offline queues at the same time. Without a lock, two concurrent
 * "read existing ids -> append new rows" sequences can interleave and each
 * overwrite the other's view of the last row, corrupting the sheet. A
 * script-wide LockService lock serializes append calls so that never happens.
 *
 * Returns the record_ids that were ACTUALLY newly written (pre-existing and
 * within-batch duplicates are reported separately in `skipped`, not counted
 * as written) — this is what lets the client's merge logic know which of its
 * queued records are now safely persisted.
 */
function actionAppend(e) {
  var body = parseJsonBody(e);
  if (!body || !Array.isArray(body)) {
    return jsonOutput({ ok: false, error: 'invalid_body' });
  }

  var sheet = getSheetByName(Contract.SHEETS.PROGRESS);
  if (!sheet) {
    return jsonOutput({ ok: false, error: 'sheet_not_found', sheet: Contract.SHEETS.PROGRESS });
  }

  var lock = LockService.getScriptLock();
  var gotLock = lock.tryLock(30000); // wait up to 30s; well under the 6-minute execution cap
  if (!gotLock) {
    return jsonOutput({ ok: false, error: 'lock_timeout' });
  }

  try {
    var existingIds = readExistingRecordIds(sheet);
    var seen = {};
    existingIds.forEach(function (id) { seen[id] = true; });

    var rowsToAppend = [];
    var written = [];
    var skipped = [];

    body.forEach(function (record) {
      var check = validateProgressRecord(record);
      if (!check.valid) {
        skipped.push({ record_id: record && record.record_id, reason: check.reason });
        return;
      }
      var id = String(record.record_id);
      if (seen[id]) {
        skipped.push({ record_id: id, reason: 'duplicate' });
        return;
      }
      seen[id] = true;
      rowsToAppend.push(Contract.PROGRESS_COLUMNS.map(function (col) { return record[col]; }));
      written.push(id);
    });

    if (rowsToAppend.length > 0) {
      sheet
        .getRange(sheet.getLastRow() + 1, 1, rowsToAppend.length, Contract.PROGRESS_COLUMNS.length)
        .setValues(rowsToAppend);
    }

    return jsonOutput({ ok: true, written: written, skipped: skipped });
  } finally {
    lock.releaseLock();
  }
}

/**
 * action=set_level (POST) — validate and write the new CEFR level to
 * settings!B1. This is the only write path for the adaptive-difficulty
 * closed loop described in the spec; Spark reads this cell every morning.
 *
 * No LockService here (unlike append): this is a single-cell overwrite, not
 * an accumulating list, so a race just means "last write wins" — no risk of
 * duplicate or lost rows, which is the failure mode LockService exists to
 * prevent for append.
 */
function actionSetLevel(e) {
  var body = parseJsonBody(e);
  if (!body || typeof body.level !== 'string') {
    return jsonOutput({ ok: false, error: 'invalid_body' });
  }
  if (!Contract.isCefrLevel(body.level)) {
    return jsonOutput({ ok: false, error: 'invalid_level', level: body.level });
  }

  var sheet = getSheetByName(Contract.SHEETS.SETTINGS);
  if (!sheet) {
    return jsonOutput({ ok: false, error: 'sheet_not_found', sheet: Contract.SHEETS.SETTINGS });
  }

  sheet.getRange(Contract.SETTINGS.LEVEL_VALUE_CELL).setValue(body.level);
  return jsonOutput({ ok: true, level: body.level });
}

/**
 * action=add_materials (POST) — batch-write freshly fetched material rows
 * into the `lessons` sheet.
 *
 * A "material row" is a lessons-sheet row with `lesson_id` intentionally
 * blank: source text + audio are ready, but no questions exist yet (see
 * docs/specs/2026-09-02-content-pipeline.md and tools/fetch-materials.js,
 * which does the fetching now that Spark can't reach VOA/BBC directly).
 * Spark turns a material row into a real lesson later by filling in
 * lesson_id, the three JSON question/vocab columns, and generated_at. See
 * also the lesson_id-empty skip added to actionLessons above, which keeps
 * these rows from being reported as broken to the web app in the meantime.
 *
 * Dedup key is `source_url` — the spec is zero-tolerance on duplicates
 * there (docs/specs/2026-09-02-content-pipeline.md, 驗收查詢). Rows whose
 * source_url already exists in the sheet, or repeats earlier in the same
 * batch, are skipped rather than written twice.
 *
 * Concurrency: same reasoning as actionAppend — without a lock, two
 * concurrent writers could both read the same "existing source_urls"
 * snapshot and each append, letting a duplicate through despite the check
 * above.
 *
 * Body shape: a JSON array of material objects, each keyed by
 * Contract.LESSON_COLUMNS names (any lesson_id sent is ignored — see below).
 */
function actionAddMaterials(e) {
  var body = parseJsonBody(e);
  if (!body || !Array.isArray(body)) {
    return jsonOutput({ ok: false, error: 'invalid_body' });
  }

  var sheet = getSheetByName(Contract.SHEETS.LESSONS);
  if (!sheet) {
    return jsonOutput({ ok: false, error: 'sheet_not_found', sheet: Contract.SHEETS.LESSONS });
  }

  var lock = LockService.getScriptLock();
  var gotLock = lock.tryLock(30000); // wait up to 30s; well under the 6-minute execution cap
  if (!gotLock) {
    return jsonOutput({ ok: false, error: 'lock_timeout' });
  }

  try {
    var idxSourceUrl = Contract.LESSON_COLUMNS.indexOf('source_url');
    var idxLessonId = Contract.LESSON_COLUMNS.indexOf('lesson_id');

    var lastRow = sheet.getLastRow();
    var seen = {};
    if (lastRow >= 2) {
      var existingUrls = sheet.getRange(2, idxSourceUrl + 1, lastRow - 1, 1).getValues();
      existingUrls.forEach(function (row) {
        if (row[0]) seen[String(row[0])] = true;
      });
    }

    var rowsToAppend = [];
    var written = [];
    var skipped = [];

    body.forEach(function (material) {
      if (!material || typeof material !== 'object') {
        skipped.push({ source_url: null, reason: 'not_object' });
        return;
      }
      var sourceUrl = material.source_url ? String(material.source_url) : '';
      if (!sourceUrl) {
        skipped.push({ source_url: null, reason: 'missing_source_url' });
        return;
      }
      if (seen[sourceUrl]) {
        skipped.push({ source_url: sourceUrl, reason: 'duplicate_source_url' });
        return;
      }
      seen[sourceUrl] = true;

      rowsToAppend.push(Contract.LESSON_COLUMNS.map(function (col, i) {
        // lesson_id stays blank no matter what the caller sent — that is
        // the definition of a material row (see doc comment above). Spark
        // fills it in later, once questions exist.
        if (i === idxLessonId) return '';
        return material[col] !== undefined && material[col] !== null ? material[col] : '';
      }));
      written.push(sourceUrl);
    });

    if (rowsToAppend.length > 0) {
      var startRow = sheet.getLastRow() + 1;

      // Sheets auto-converts a date-looking string written into a cell to a
      // real Date object. lesson_id is blank here, but Spark later writes an
      // actual YYYY-MM-DD string into this same cell — force the column to
      // plain text now so that write lands as a string, not a Date (this
      // has already caused a real bug once).
      sheet.getRange(startRow, idxLessonId + 1, rowsToAppend.length, 1).setNumberFormat('@');

      sheet
        .getRange(startRow, 1, rowsToAppend.length, Contract.LESSON_COLUMNS.length)
        .setValues(rowsToAppend);
    }

    return jsonOutput({ ok: true, written: written, skipped: skipped });
  } finally {
    lock.releaseLock();
  }
}

// ---------------------------------------------------------------------------
// Sheet helpers
// ---------------------------------------------------------------------------

function getSpreadsheet() {
  var explicitId = PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');
  if (explicitId) {
    return SpreadsheetApp.openById(explicitId);
  }
  var active = SpreadsheetApp.getActiveSpreadsheet();
  if (!active) {
    throw new Error(
      'no_spreadsheet_configured: this script is not bound to a spreadsheet and ' +
        'no SPREADSHEET_ID script property is set'
    );
  }
  return active;
}

function getSheetByName(name) {
  return getSpreadsheet().getSheetByName(name);
}

function readExistingRecordIds(sheet) {
  var lastRow = sheet.getLastRow();
  if (lastRow < 2) return [];
  var values = sheet.getRange(2, 1, lastRow - 1, 1).getValues();
  return values.map(function (r) { return String(r[0]); });
}

function rowToProgressRecord(row) {
  var record = {};
  Contract.PROGRESS_COLUMNS.forEach(function (col, i) {
    record[col] = row[i];
  });
  return record;
}

/**
 * Minimal shape check before a record is trusted enough to write to Sheets.
 * Anything that fails this is skipped (reported in `skipped`, not an error
 * that aborts the whole batch) — one malformed queued record from a buggy
 * client build should never block every other record in the same upload.
 */
function validateProgressRecord(record) {
  if (!record || typeof record !== 'object') return { valid: false, reason: 'not_object' };
  if (!record.record_id) return { valid: false, reason: 'missing_record_id' };
  if (Contract.ITEM_TYPES.indexOf(record.item_type) === -1) return { valid: false, reason: 'bad_item_type' };
  if (!record.item_id) return { valid: false, reason: 'missing_item_id' };
  if (!record.lesson_id) return { valid: false, reason: 'missing_lesson_id' };
  if (!record.answered_at) return { valid: false, reason: 'missing_answered_at' };
  if (typeof record.correct !== 'boolean') return { valid: false, reason: 'bad_correct' };
  if (!record.device) return { valid: false, reason: 'missing_device' };
  if (!record.client_version) return { valid: false, reason: 'missing_client_version' };
  return { valid: true };
}

function parseJsonBody(e) {
  try {
    if (!e || !e.postData || !e.postData.contents) return null;
    return JSON.parse(e.postData.contents);
  } catch (err) {
    return null;
  }
}

function jsonOutput(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}

// ---------------------------------------------------------------------------
// Token verification
// ---------------------------------------------------------------------------

function isValidToken(token) {
  var expected = PropertiesService.getScriptProperties().getProperty('SYNC_TOKEN');
  if (!expected || !token) return false;
  return safeCompare(String(token), String(expected));
}

/**
 * Constant-time-ish string comparison: walks the full length of both
 * strings and only branches on the accumulated result at the very end,
 * instead of `return false` on the first mismatching character. This is the
 * standard mitigation for timing side-channel attacks on token comparison.
 *
 * Caveat: this is a best-effort implementation, not a guarantee. Apps
 * Script's V8 runtime exposes no low-level timing-safe-compare primitive
 * (unlike e.g. Node's crypto.timingSafeEqual), and JS engines are free to
 * optimize this loop in ways that could reintroduce data-dependent timing.
 * Given the token is a long random string and this is a personal single-user
 * project (not a high-value target), this is judged sufficient — a true
 * constant-time guarantee is not achievable from pure Apps Script code.
 */
function safeCompare(a, b) {
  var lenA = a.length;
  var lenB = b.length;
  var maxLen = Math.max(lenA, lenB);
  var result = lenA === lenB ? 0 : 1;
  for (var i = 0; i < maxLen; i++) {
    var charA = i < lenA ? a.charCodeAt(i) : 0;
    var charB = i < lenB ? b.charCodeAt(i) : 0;
    result |= charA ^ charB;
  }
  return result === 0;
}

// ---------------------------------------------------------------------------
// One-time setup utilities — run manually from the Apps Script editor
// ---------------------------------------------------------------------------

/**
 * Creates the lessons / progress / settings sheets with header rows matching
 * the Contract column order, if they don't already exist. Safe to re-run:
 * it never touches a sheet or header that's already there.
 */
function setupSheets() {
  var ss = getSpreadsheet();

  var lessons = getOrCreateSheet(ss, Contract.SHEETS.LESSONS);
  ensureHeaderRow(lessons, Contract.LESSON_COLUMNS);

  var progress = getOrCreateSheet(ss, Contract.SHEETS.PROGRESS);
  ensureHeaderRow(progress, Contract.PROGRESS_COLUMNS);

  var settings = getOrCreateSheet(ss, Contract.SHEETS.SETTINGS);
  var labelCell = settings.getRange(Contract.SETTINGS.LEVEL_LABEL_CELL);
  if (!labelCell.getValue()) {
    labelCell.setValue(Contract.SETTINGS.LEVEL_LABEL);
  }
  var valueCell = settings.getRange(Contract.SETTINGS.LEVEL_VALUE_CELL);
  if (!valueCell.getValue()) {
    valueCell.setValue(Contract.DEFAULT_LEVEL);
  }

  Logger.log('Sheets ready: ' + Contract.SHEETS.LESSONS + ', ' + Contract.SHEETS.PROGRESS + ', ' + Contract.SHEETS.SETTINGS);

  // A brand-new spreadsheet still carries its default "工作表1"/"Sheet1" tab.
  // It does no harm to this script, but it has already caused one real
  // failure in practice: Gemini Spark picked that tab instead of `lessons`,
  // so its write landed somewhere the owner never looks. Report extras
  // rather than deleting them -- a tab may hold something put there on
  // purpose, and deleting a sheet cannot be undone from here.
  var known = [
    Contract.SHEETS.LESSONS,
    Contract.SHEETS.PROGRESS,
    Contract.SHEETS.SETTINGS,
    'audio_log'
  ];
  var extras = ss.getSheets()
    .map(function (s) { return s.getName(); })
    .filter(function (name) { return known.indexOf(name) === -1; });

  if (extras.length) {
    Logger.log(
      '注意：這份試算表還有本系統用不到的分頁：' + extras.join('、') +
      '。新建試算表預設的「工作表1」留著會讓 Gemini Spark 有機會寫錯分頁，' +
      '若不是你自己要用的，建議手動刪除。'
    );
  }
}

function getOrCreateSheet(ss, name) {
  var sheet = ss.getSheetByName(name);
  if (!sheet) {
    sheet = ss.insertSheet(name);
  }
  return sheet;
}

function ensureHeaderRow(sheet, columns) {
  var existing = sheet.getRange(1, 1, 1, columns.length).getValues()[0];
  var hasHeader = existing.some(function (v) { return v !== '' && v !== null; });
  if (!hasHeader) {
    sheet.getRange(1, 1, 1, columns.length).setValues([columns]);
  }
}

/**
 * Generates a long random sync token, stores it in Script Properties (so
 * isValidToken() picks it up immediately), and logs it so the user can copy
 * it into every device's local config. Re-running this rotates the token —
 * every device must be updated afterwards, or they'll start seeing
 * {ok:false, error:'forbidden'}.
 */
function generateToken() {
  var token = Utilities.getUuid().replace(/-/g, '') + Utilities.getUuid().replace(/-/g, '');
  PropertiesService.getScriptProperties().setProperty('SYNC_TOKEN', token);
  Logger.log('New SYNC_TOKEN generated and saved to Script Properties.');
  Logger.log('Copy this into js/config.local.js on every device that syncs:');
  Logger.log(token);
  return token;
}
